on:
  push:
    branches:
      - master

name: Package and deploy simple web app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - uses: actions/checkout@master

    # deploy web app using publish profile credentials
    - uses: azure/webapps-deploy@v1
      with:
        app-name: KuvNodeWin
        package: .
        publish-profile: ${{ secrets.AZURE_CREDENTIALS_34c1cafa-1b71-4a }}